export type BillingCycle = "monthly" | "yearly" | "weekly";
export type Category =
  | "Eğlence"
  | "Müzik"
  | "Yazılım"
  | "Oyun"
  | "Eğitim"
  | "Üretkenlik"
  | "Bulut"
  | "Sağlık"
  | "Haber"
  | "Alışveriş"
  | "Spor"
  | "Diğer";

export interface ServiceTemplate {
  id: string;
  name: string;
  domain: string;
  category: Category;
  color: string;
  typical_price_try: number;
  typical_price_usd: number;
  billing_cycle: BillingCycle;
  keywords: string[];
}

export const SERVICE_TEMPLATES: ServiceTemplate[] = [
  // === EĞLENCE ===
  {
    id: "netflix",
    name: "Netflix",
    domain: "netflix.com",
    category: "Eğlence",
    color: "#E50914",
    typical_price_try: 199.99,
    typical_price_usd: 15.49,
    billing_cycle: "monthly",
    keywords: ["netflix", "dizi", "film", "streaming"],
  },
  {
    id: "disney-plus",
    name: "Disney+",
    domain: "disneyplus.com",
    category: "Eğlence",
    color: "#0063E5",
    typical_price_try: 129.99,
    typical_price_usd: 13.99,
    billing_cycle: "monthly",
    keywords: ["disney", "marvel", "star wars"],
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime",
    domain: "amazon.com",
    category: "Eğlence",
    color: "#FF9900",
    typical_price_try: 69.99,
    typical_price_usd: 14.99,
    billing_cycle: "monthly",
    keywords: ["amazon", "prime", "video"],
  },
  {
    id: "hbo-max",
    name: "Max (HBO)",
    domain: "max.com",
    category: "Eğlence",
    color: "#002BE7",
    typical_price_try: 149.99,
    typical_price_usd: 15.99,
    billing_cycle: "monthly",
    keywords: ["hbo", "max", "warner"],
  },
  {
    id: "hulu",
    name: "Hulu",
    domain: "hulu.com",
    category: "Eğlence",
    color: "#1CE783",
    typical_price_try: 89.99,
    typical_price_usd: 7.99,
    billing_cycle: "monthly",
    keywords: ["hulu"],
  },
  {
    id: "apple-tv",
    name: "Apple TV+",
    domain: "apple.com/apple-tv-plus",
    category: "Eğlence",
    color: "#000000",
    typical_price_try: 109.99,
    typical_price_usd: 9.99,
    billing_cycle: "monthly",
    keywords: ["apple tv", "appletv"],
  },
  {
    id: "blutv",
    name: "BluTV",
    domain: "blutv.com",
    category: "Eğlence",
    color: "#1A73E8",
    typical_price_try: 99.99,
    typical_price_usd: 5.0,
    billing_cycle: "monthly",
    keywords: ["blutv", "blu"],
  },
  {
    id: "gain",
    name: "Gain",
    domain: "gain.tv",
    category: "Eğlence",
    color: "#FF6600",
    typical_price_try: 49.99,
    typical_price_usd: 3.0,
    billing_cycle: "monthly",
    keywords: ["gain", "acun"],
  },
  {
    id: "mubi",
    name: "MUBI",
    domain: "mubi.com",
    category: "Eğlence",
    color: "#000000",
    typical_price_try: 89.99,
    typical_price_usd: 10.99,
    billing_cycle: "monthly",
    keywords: ["mubi", "sanat film"],
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    domain: "youtube.com",
    category: "Eğlence",
    color: "#FF0000",
    typical_price_try: 79.99,
    typical_price_usd: 13.99,
    billing_cycle: "monthly",
    keywords: ["youtube", "yt premium"],
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    domain: "crunchyroll.com",
    category: "Eğlence",
    color: "#F47521",
    typical_price_try: 79.99,
    typical_price_usd: 7.99,
    billing_cycle: "monthly",
    keywords: ["crunchyroll", "anime"],
  },

  // === MÜZİK ===
  {
    id: "spotify",
    name: "Spotify",
    domain: "spotify.com",
    category: "Müzik",
    color: "#1DB954",
    typical_price_try: 59.99,
    typical_price_usd: 9.99,
    billing_cycle: "monthly",
    keywords: ["spotify", "müzik", "podcast"],
  },
  {
    id: "apple-music",
    name: "Apple Music",
    domain: "apple.com/apple-music",
    category: "Müzik",
    color: "#FC3C44",
    typical_price_try: 69.99,
    typical_price_usd: 10.99,
    billing_cycle: "monthly",
    keywords: ["apple music", "itunes"],
  },
  {
    id: "youtube-music",
    name: "YouTube Music",
    domain: "music.youtube.com",
    category: "Müzik",
    color: "#FF0000",
    typical_price_try: 59.99,
    typical_price_usd: 10.99,
    billing_cycle: "monthly",
    keywords: ["youtube music"],
  },
  {
    id: "tidal",
    name: "Tidal",
    domain: "tidal.com",
    category: "Müzik",
    color: "#000000",
    typical_price_try: 79.99,
    typical_price_usd: 10.99,
    billing_cycle: "monthly",
    keywords: ["tidal", "hifi müzik"],
  },
  {
    id: "deezer",
    name: "Deezer",
    domain: "deezer.com",
    category: "Müzik",
    color: "#FF0092",
    typical_price_try: 49.99,
    typical_price_usd: 9.99,
    billing_cycle: "monthly",
    keywords: ["deezer"],
  },

  // === YAZILIM / ÜRETKENLİK ===
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    domain: "microsoft.com",
    category: "Üretkenlik",
    color: "#D83B01",
    typical_price_try: 179.99,
    typical_price_usd: 9.99,
    billing_cycle: "monthly",
    keywords: ["microsoft", "office", "365", "word", "excel"],
  },
  {
    id: "adobe-cc",
    name: "Adobe Creative Cloud",
    domain: "adobe.com",
    category: "Yazılım",
    color: "#FF0000",
    typical_price_try: 599.99,
    typical_price_usd: 54.99,
    billing_cycle: "monthly",
    keywords: ["adobe", "photoshop", "illustrator", "premiere", "creative cloud"],
  },
  {
    id: "notion",
    name: "Notion",
    domain: "notion.so",
    category: "Üretkenlik",
    color: "#000000",
    typical_price_try: 159.99,
    typical_price_usd: 16.0,
    billing_cycle: "monthly",
    keywords: ["notion", "not", "wiki"],
  },
  {
    id: "figma",
    name: "Figma",
    domain: "figma.com",
    category: "Yazılım",
    color: "#F24E1E",
    typical_price_try: 349.99,
    typical_price_usd: 15.0,
    billing_cycle: "monthly",
    keywords: ["figma", "tasarım", "ui", "ux"],
  },
  {
    id: "github",
    name: "GitHub Pro",
    domain: "github.com",
    category: "Yazılım",
    color: "#181717",
    typical_price_try: 109.99,
    typical_price_usd: 4.0,
    billing_cycle: "monthly",
    keywords: ["github", "git", "kod"],
  },
  {
    id: "jetbrains",
    name: "JetBrains All Products",
    domain: "jetbrains.com",
    category: "Yazılım",
    color: "#000000",
    typical_price_try: 449.99,
    typical_price_usd: 28.9,
    billing_cycle: "monthly",
    keywords: ["jetbrains", "intellij", "webstorm", "pycharm"],
  },
  {
    id: "linear",
    name: "Linear",
    domain: "linear.app",
    category: "Üretkenlik",
    color: "#5E6AD2",
    typical_price_try: 179.99,
    typical_price_usd: 8.0,
    billing_cycle: "monthly",
    keywords: ["linear", "proje yönetim"],
  },
  {
    id: "slack",
    name: "Slack",
    domain: "slack.com",
    category: "Üretkenlik",
    color: "#4A154B",
    typical_price_try: 259.99,
    typical_price_usd: 7.25,
    billing_cycle: "monthly",
    keywords: ["slack", "mesajlaşma", "iletişim"],
  },
  {
    id: "zoom",
    name: "Zoom",
    domain: "zoom.us",
    category: "Üretkenlik",
    color: "#2D8CFF",
    typical_price_try: 449.99,
    typical_price_usd: 14.99,
    billing_cycle: "monthly",
    keywords: ["zoom", "toplantı", "video call"],
  },

  // === BULUT ===
  {
    id: "google-one",
    name: "Google One",
    domain: "one.google.com",
    category: "Bulut",
    color: "#4285F4",
    typical_price_try: 49.99,
    typical_price_usd: 2.99,
    billing_cycle: "monthly",
    keywords: ["google one", "google drive", "depolama"],
  },
  {
    id: "icloud",
    name: "iCloud+",
    domain: "apple.com/icloud",
    category: "Bulut",
    color: "#3693F3",
    typical_price_try: 39.99,
    typical_price_usd: 2.99,
    billing_cycle: "monthly",
    keywords: ["icloud", "apple depolama"],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    domain: "dropbox.com",
    category: "Bulut",
    color: "#0061FF",
    typical_price_try: 349.99,
    typical_price_usd: 11.99,
    billing_cycle: "monthly",
    keywords: ["dropbox", "bulut depolama"],
  },

  // === OYUN ===
  {
    id: "xbox-game-pass",
    name: "Xbox Game Pass Ultimate",
    domain: "xbox.com",
    category: "Oyun",
    color: "#107C10",
    typical_price_try: 199.99,
    typical_price_usd: 19.99,
    billing_cycle: "monthly",
    keywords: ["xbox", "game pass", "microsoft gaming"],
  },
  {
    id: "playstation-plus",
    name: "PlayStation Plus",
    domain: "playstation.com",
    category: "Oyun",
    color: "#003791",
    typical_price_try: 179.99,
    typical_price_usd: 14.99,
    billing_cycle: "monthly",
    keywords: ["playstation", "ps plus", "psn"],
  },
  {
    id: "nintendo-switch-online",
    name: "Nintendo Switch Online",
    domain: "nintendo.com",
    category: "Oyun",
    color: "#E60012",
    typical_price_try: 99.99,
    typical_price_usd: 3.99,
    billing_cycle: "monthly",
    keywords: ["nintendo", "switch online"],
  },
  {
    id: "ea-play",
    name: "EA Play",
    domain: "ea.com",
    category: "Oyun",
    color: "#FF4747",
    typical_price_try: 69.99,
    typical_price_usd: 4.99,
    billing_cycle: "monthly",
    keywords: ["ea play", "ea sports", "electronic arts"],
  },

  // === EĞİTİM ===
  {
    id: "duolingo",
    name: "Duolingo Plus",
    domain: "duolingo.com",
    category: "Eğitim",
    color: "#58CC02",
    typical_price_try: 119.99,
    typical_price_usd: 6.99,
    billing_cycle: "monthly",
    keywords: ["duolingo", "dil öğrenme"],
  },
  {
    id: "udemy",
    name: "Udemy",
    domain: "udemy.com",
    category: "Eğitim",
    color: "#A435F0",
    typical_price_try: 299.99,
    typical_price_usd: 29.99,
    billing_cycle: "monthly",
    keywords: ["udemy", "kurs", "eğitim"],
  },
  {
    id: "coursera",
    name: "Coursera Plus",
    domain: "coursera.org",
    category: "Eğitim",
    color: "#0056D2",
    typical_price_try: 1299.99,
    typical_price_usd: 59.0,
    billing_cycle: "monthly",
    keywords: ["coursera", "üniversite", "sertifika"],
  },
  {
    id: "linkedin-learning",
    name: "LinkedIn Learning",
    domain: "linkedin.com",
    category: "Eğitim",
    color: "#0A66C2",
    typical_price_try: 199.99,
    typical_price_usd: 26.99,
    billing_cycle: "monthly",
    keywords: ["linkedin learning", "linkedin premium"],
  },

  // === SAĞLIK ===
  {
    id: "headspace",
    name: "Headspace",
    domain: "headspace.com",
    category: "Sağlık",
    color: "#F47D31",
    typical_price_try: 229.99,
    typical_price_usd: 12.99,
    billing_cycle: "monthly",
    keywords: ["headspace", "meditasyon"],
  },
  {
    id: "calm",
    name: "Calm",
    domain: "calm.com",
    category: "Sağlık",
    color: "#4A90D9",
    typical_price_try: 449.99,
    typical_price_usd: 14.99,
    billing_cycle: "yearly",
    keywords: ["calm", "meditasyon", "uyku"],
  },

  // === HABER ===
  {
    id: "new-york-times",
    name: "New York Times",
    domain: "nytimes.com",
    category: "Haber",
    color: "#000000",
    typical_price_try: 129.99,
    typical_price_usd: 17.0,
    billing_cycle: "monthly",
    keywords: ["nyt", "new york times", "gazete"],
  },

  // === SPOR ===
  {
    id: "nba-league-pass",
    name: "NBA League Pass",
    domain: "nba.com",
    category: "Spor",
    color: "#C9082A",
    typical_price_try: 399.99,
    typical_price_usd: 28.99,
    billing_cycle: "monthly",
    keywords: ["nba", "basketbol"],
  },
  {
    id: "strava",
    name: "Strava Premium",
    domain: "strava.com",
    category: "Spor",
    color: "#FC4C02",
    typical_price_try: 79.99,
    typical_price_usd: 11.99,
    billing_cycle: "monthly",
    keywords: ["strava", "koşu", "bisiklet", "spor"],
  },
];
